services:
  postgres:
    container_name: fynn-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fynn
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: fynn-adminer
    image: adminer
    restart: always
    ports:
      - 5000:5000

volumes:
  postgres_data:
